services:
  - type: web
    name: news-scraper
    env: python
    plan: free
    region: singapore  # or choose closest to your location
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
    healthCheckPath: /
    autoDeploy: true
